# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bugsnag/all/bugsnag.rbi
#
# bugsnag-6.23.0

module Bugsnag
  def self.abort_reason(exception, auto_notify); end
  def self.add_on_breadcrumb(callback); end
  def self.add_on_error(callback); end
  def self.at_exit_handler_installed?; end
  def self.before_notify_callbacks; end
  def self.breadcrumbs; end
  def self.check_endpoint_setup; end
  def self.check_key_valid; end
  def self.cleaner; end
  def self.configuration; end
  def self.configure(validate_api_key = nil); end
  def self.deliver_notification(report); end
  def self.leave_breadcrumb(name, meta_data = nil, type = nil, auto = nil); end
  def self.load_integration(integration); end
  def self.load_integrations; end
  def self.notify(exception, auto_notify = nil, &block); end
  def self.register_at_exit; end
  def self.remove_on_breadcrumb(callback); end
  def self.remove_on_error(callback); end
  def self.report_to_json(report); end
  def self.session_tracker; end
  def self.should_deliver_notification?(exception, auto_notify); end
  def self.start_session; end
  def self.unwrap_bundler_exception(exception); end
end
class Bugsnag::OnErrorCallbacks
  def call(report); end
  def initialize(next_middleware, callbacks); end
end
class Bugsnag::MiddlewareStack
  def disable(*middlewares); end
  def initialize; end
  def insert_after(after, new_middleware); end
  def insert_before(before, new_middleware); end
  def method_missing(method, *args, &block); end
  def middleware_procs; end
  def remove(*middlewares); end
  def run(report); end
  def use(new_middleware); end
end
module Bugsnag::Middleware
end
class Bugsnag::Middleware::Callbacks
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::DiscardErrorClass
  def call(report); end
  def initialize(middleware); end
end
class Bugsnag::Middleware::ExceptionMetaData
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::IgnoreErrorClass
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::SuggestionData
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::ClassifyError
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::SessionData
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::Breadcrumbs
  def call(report); end
  def initialize(next_callable); end
end
module Bugsnag::Utility
end
class Bugsnag::Utility::CircularBuffer
  def <<(item); end
  def each(&block); end
  def initialize(max_items = nil); end
  def max_items; end
  def max_items=(new_max_items); end
  def trim_buffer; end
  include Enumerable
end
module Bugsnag::Breadcrumbs
end
class Bugsnag::Breadcrumbs::OnBreadcrumbCallbackList
  def add(callback); end
  def call(breadcrumb); end
  def initialize(configuration); end
  def remove(callback); end
end
class Bugsnag::Configuration
  def add_on_breadcrumb(callback); end
  def add_on_error(callback); end
  def api_key; end
  def api_key=(arg0); end
  def app_type; end
  def app_type=(app_type); end
  def app_version; end
  def app_version=(arg0); end
  def auto_capture_sessions; end
  def auto_capture_sessions=(arg0); end
  def auto_notify; end
  def auto_notify=(arg0); end
  def auto_track_sessions; end
  def auto_track_sessions=(track_sessions); end
  def before_breadcrumb_callbacks; end
  def before_breadcrumb_callbacks=(arg0); end
  def breadcrumbs; end
  def ca_file; end
  def ca_file=(arg0); end
  def clear_request_data; end
  def context; end
  def context=(arg0); end
  def context_set?; end
  def debug(message); end
  def default_delivery_method=(delivery_method); end
  def default_hostname; end
  def delivery_method; end
  def delivery_method=(delivery_method); end
  def detected_app_type; end
  def detected_app_type=(app_type); end
  def disable_sessions; end
  def discard_classes; end
  def discard_classes=(arg0); end
  def enable_sessions; end
  def enabled_automatic_breadcrumb_types; end
  def enabled_automatic_breadcrumb_types=(arg0); end
  def enabled_breadcrumb_types; end
  def enabled_breadcrumb_types=(breadcrumb_types); end
  def enabled_release_stages; end
  def enabled_release_stages=(release_stages); end
  def endpoint; end
  def endpoint=(new_notify_endpoint); end
  def error(message); end
  def hostname; end
  def hostname=(arg0); end
  def ignore_classes; end
  def ignore_classes=(arg0); end
  def info(message); end
  def initialize; end
  def internal_middleware; end
  def internal_middleware=(arg0); end
  def logger; end
  def logger=(arg0); end
  def max_breadcrumbs; end
  def max_breadcrumbs=(new_max_breadcrumbs); end
  def meta_data_filters; end
  def meta_data_filters=(arg0); end
  def middleware; end
  def middleware=(arg0); end
  def notify_endpoint; end
  def notify_release_stages; end
  def notify_release_stages=(arg0); end
  def on_breadcrumb_callbacks; end
  def parse_proxy(uri); end
  def project_root; end
  def project_root=(arg0); end
  def proxy_host; end
  def proxy_host=(arg0); end
  def proxy_password; end
  def proxy_password=(arg0); end
  def proxy_port; end
  def proxy_port=(arg0); end
  def proxy_user; end
  def proxy_user=(arg0); end
  def release_stage; end
  def release_stage=(arg0); end
  def remove_on_breadcrumb(callback); end
  def remove_on_error(callback); end
  def request_data; end
  def runtime_versions; end
  def runtime_versions=(arg0); end
  def scopes_to_filter; end
  def scopes_to_filter=(arg0); end
  def send_code; end
  def send_code=(arg0); end
  def send_environment; end
  def send_environment=(arg0); end
  def session_endpoint; end
  def session_endpoint=(new_session_endpoint); end
  def set_endpoints(new_notify_endpoint, new_session_endpoint); end
  def set_request_data(key, value); end
  def should_notify_release_stage?; end
  def timeout; end
  def timeout=(arg0); end
  def track_sessions; end
  def track_sessions=(arg0); end
  def unset_request_data(key, value); end
  def valid_api_key?; end
  def vendor_path; end
  def vendor_path=(arg0); end
  def warn(message); end
end
module Bugsnag::MetaData
  def bugsnag_context; end
  def bugsnag_context=(arg0); end
  def bugsnag_grouping_hash; end
  def bugsnag_grouping_hash=(arg0); end
  def bugsnag_meta_data; end
  def bugsnag_meta_data=(arg0); end
  def bugsnag_user_id; end
  def bugsnag_user_id=(arg0); end
end
class Bugsnag::Error
  def error_class; end
  def error_class=(arg0); end
  def error_message; end
  def error_message=(arg0); end
  def initialize(error_class, error_message, stacktrace); end
  def stacktrace; end
  def type; end
  def type=(arg0); end
end
class Bugsnag::CodeExtractor
  def add_file(path, trace); end
  def associate_code_with_trace(code, traces); end
  def extract!; end
  def extract_from(path, traces, line_numbers); end
  def initialize(configuration); end
  def trim_excess_lines(code, line_number); end
end
module Bugsnag::Stacktrace
  def self.process(backtrace, configuration); end
end
class Bugsnag::Report
  def add_metadata(section, key_or_data, *args); end
  def add_tab(name, value); end
  def api_key; end
  def api_key=(arg0); end
  def app_type; end
  def app_type=(arg0); end
  def app_version; end
  def app_version=(arg0); end
  def as_json; end
  def automatic_context; end
  def automatic_context=(arg0); end
  def breadcrumbs; end
  def breadcrumbs=(arg0); end
  def clear_metadata(section, *args); end
  def configuration; end
  def configuration=(arg0); end
  def context; end
  def context=(arg0); end
  def delivery_method; end
  def delivery_method=(arg0); end
  def error_class(exception); end
  def errors; end
  def exceptions; end
  def exceptions=(arg0); end
  def generate_error_list; end
  def generate_exception_list; end
  def generate_raw_exceptions(exception); end
  def grouping_hash; end
  def grouping_hash=(arg0); end
  def headers; end
  def hostname; end
  def hostname=(arg0); end
  def ignore!; end
  def ignore?; end
  def initialize(exception, passed_configuration, auto_notify = nil); end
  def meta_data; end
  def meta_data=(arg0); end
  def metadata; end
  def metadata=(metadata); end
  def original_error; end
  def raw_exceptions; end
  def raw_exceptions=(arg0); end
  def release_stage; end
  def release_stage=(arg0); end
  def remove_tab(name); end
  def request; end
  def request_data; end
  def runtime_versions; end
  def runtime_versions=(arg0); end
  def session; end
  def session=(arg0); end
  def set_user(id = nil, email = nil, name = nil); end
  def severity; end
  def severity=(arg0); end
  def severity_reason; end
  def severity_reason=(arg0); end
  def summary; end
  def unhandled; end
  def user; end
  def user=(arg0); end
end
class Bugsnag::Cleaner
  def clean_object(object); end
  def clean_string(str); end
  def clean_url(url); end
  def deep_filters?; end
  def filters_match?(key); end
  def filters_match_deeply?(key, scope); end
  def initialize(configuration); end
  def scope_should_be_filtered?(scope); end
  def traverse_object(obj, seen, scope); end
end
module Bugsnag::Helpers
  def self.deep_merge!(l_hash, r_hash); end
  def self.deep_merge(l_hash, r_hash); end
  def self.extract_exception(payload, &block); end
  def self.get_payload_length(value); end
  def self.is_json_raw_type?(value); end
  def self.payload_too_long?(value); end
  def self.remove_metadata_from_events(object); end
  def self.trim_as_string(text); end
  def self.trim_if_needed(value); end
  def self.trim_metadata(payload); end
  def self.trim_stacktrace_code(payload); end
  def self.trim_stacktrace_functions(payload); end
  def self.trim_strings_in_array(collection); end
  def self.trim_strings_in_hash(hash); end
  def self.trim_strings_in_value(value); end
  def self.truncate_array(array); end
  def self.truncate_arrays_in_hash(hash); end
  def self.truncate_arrays_in_value(value); end
  def self.truncate_exception_messages(payload); end
end
class Bugsnag::SessionTracker
  def add_session(min); end
  def create_session; end
  def deliver(session_payload); end
  def initialize; end
  def self.get_current_session; end
  def self.set_current_session(session); end
  def send_sessions; end
  def session_counts; end
  def start_delivery_thread; end
  def start_session; end
end
module Bugsnag::Delivery
  def self.[](name); end
  def self.delivery_methods; end
  def self.register(name, delivery_method); end
end
class Bugsnag::Delivery::Synchronous
  def self.default_headers; end
  def self.deliver(url, body, configuration, options = nil); end
  def self.path(uri); end
  def self.request(url, body, configuration, options); end
end
class Bugsnag::Delivery::ThreadQueue < Bugsnag::Delivery::Synchronous
  def self.serialize_and_deliver(url, get_payload, configuration, options = nil); end
  def self.start_once!; end
end
class Bugsnag::Rack
  def call(env); end
  def initialize(app); end
end
class Bugsnag::Middleware::RackRequest
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::WardenUser
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::ClearanceUser
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::Rails3Request
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::Sidekiq
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::Mailman
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::Rake
  def call(report); end
  def initialize(bugsnag); end
end
class Bugsnag::Middleware::DelayedJob
  def call(report); end
  def construct_job_payload(payload); end
  def get_context(payload_data, active_job_data); end
  def initialize(bugsnag); end
end
module Bugsnag::BreadcrumbType
end
class Bugsnag::Breadcrumbs::Validator
  def initialize(configuration); end
  def validate(breadcrumb); end
end
class Bugsnag::Breadcrumbs::Breadcrumb
  def auto; end
  def ignore!; end
  def ignore?; end
  def initialize(name, type, meta_data, auto); end
  def message; end
  def message=(message); end
  def meta_data; end
  def meta_data=(arg0); end
  def metadata; end
  def metadata=(metadata); end
  def name; end
  def name=(arg0); end
  def timestamp; end
  def to_h; end
  def type; end
  def type=(arg0); end
end
class Bugsnag::Utility::MetadataDelegate
  def add_metadata(metadata, section, key_or_data, value = nil); end
  def clear_metadata(metadata, section, key = nil); end
  def merge_metadata(existing_metadata, section, new_metadata); end
  def overwrite_metadata(metadata, section, key, value); end
end
