# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `liquid` gem.
# Please instead update this file by running `bin/tapioca gem liquid`.

class FalseClass
  include ::JSON::Ext::Generator::GeneratorMethods::FalseClass
end

class NilClass
  include ::JSON::Ext::Generator::GeneratorMethods::NilClass
end

class Numeric
  include ::Comparable
end

class Symbol
  include ::Comparable
end

class TrueClass
  include ::JSON::Ext::Generator::GeneratorMethods::TrueClass
end
