# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/shopify-cli/all/shopify-cli.rbi
#
# shopify-cli-2.7.4

module Extension
end
class Extension::PackageResolutionFailed < RuntimeError
end
class Extension::Project < ShopifyCLI::ProjectType
end
class Extension::Command < ShopifyCLI::Command::ProjectCommand
end
module Extension::Tasks
end
module Extension::Tasks::Converters
end
module Extension::Tasks::ExecuteCommands
end
module Extension::Forms
end
module Extension::Forms::Questions
end
module Extension::Features
end
module Extension::Features::Runtimes
end
module Extension::Models
end
module Extension::Models::SpecificationHandlers
end
module Extension::Models::ServerConfig
end
module Extension::Loaders
end
