# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sys-uname` gem.
# Please instead update this file by running `bin/tapioca gem sys-uname`.

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca/wiki/Manual-Gem-Requires
