# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `theme-check` gem.
# Please instead update this file by running `bin/tapioca gem theme-check`.

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca/wiki/Manual-Gem-Requires
