name: dev
type:
  - ruby

env:
  SHOPIFY_CLI_DEVELOPMENT: "1"

up:
  - ruby: 2.7.1
  - homebrew:
      - dpkg:
          version: 1.20.9
      - rpm:
          version: 4.16.1.3
  - bundler
  - node:
      version: 14.9.0
      yarn: true
  - docker

test:
  desc: "Run tests."
  run: |
    if [ "$#" -eq 1 ] && [[ -f $1 ]];
    then
      bundle exec rake test TEST=$1
    else
      bundle exec rake test $@
    fi

commands:
  style:
    run: bundle exec rubocop .
