name: dev
type:
  - ruby

env:
  SHOPIFY_CLI_DEVELOPMENT: "1"

up:
  - ruby: 2.7.5
  - homebrew:
      - dpkg:
          version: 1.21.1
      # commenting out rpm to dev up on m1s, this is only needed for releases
      # - rpm:
      #     version: 4.17.0
  - bundler
  - docker

test:
  desc: "Run tests."
  run: |
    if [ "$#" -eq 1 ] && [[ -f $1 ]];
    then
      bundle exec rake test TEST=$1
    else
      bundle exec rake test $@
    fi

commands:
  style:
    run: bundle exec rubocop .
  test:script:
    desc: "Run all script-related tests"
    run: TEST='test/project_types/script/**/*.rb' bundle exec rake test $@
